# Generated by Django 3.1.7 on 2021-02-23 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_counter', '0002_auto_20210223_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(null=True, upload_to='img'),
        ),
    ]
